export const REQUEST_SEARCH = 'UNLOCK/REQUEST_API';
export const RECEIVE_RESPONSE = 'UNLOCK/RECEIVE_RESPONSE';
export const REQUEST_UNLOCK = 'UNLOCK/REQUEST_UNLOCK';
export const DISMISS_ALERT = 'DISMISS_ALERT';
export const EMPTY_DATA_SEARCH = 'EMPTY_DATA_SEARCH';

